alertmanager:
  alertmanagerSpec:
    secrets:
      - alertmanager-slack-creds
  config:
    global:
      resolve_timeout: 5m
      slack_api_url_file: "/etc/alertmanager/secrets/alertmanager-slack-creds/slack_api_url"
    route:
      receiver: "slack"
      group_by: ["alertname", "namespace", "pod", "instance"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
    receivers:
      - name: "slack"
        slack_configs:
          - channel: "#homelab-alerts"
            send_resolved: true
            title: "{{ .CommonLabels.alertname }} ({{ .Status }})"
            text: "{{ range .Alerts }}â€¢ {{ .Annotations.summary }}\n{{ end }}"

