services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    command: tunnel run ssh-tunnel
    restart: unless-stopped
    network_mode: host
    user: "${UID}:${GID}"
    volumes:
      - ./cloudflared:/etc/cloudflared
      - type: bind
        source: ${HOME}/.cloudflared/cert.pem
        target: /etc/cloudflared/cert.pem
        read_only: true
